site_name: Naruto Grupo 3

theme:
  name: material
  logo: images/naruto_logo_small.png
  palette:
    primary: "deep orange"
    accent: "deep purple"
  features:
    - navigation.tabs

nav:
  - Home: index.md
  - Políticas de Contribuição: policies.md
  - Módulo 1:
    - Modelo Entidade-Relacionamento (MER): modulo1/diagrama_entidade_relacionamento.md
    - Modelo Relacional: modulo1/modelo_relacional.md
    - Dicionário de Dados: modulo1/dicionario_de_dados.md
    - Normalização: "modulo1/normalizacao.md"
  - Módulo 2:
    - SQL:
      - DDL: modulo2/sql/ddl.md
