name: github-pages update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  install_pipenv_refs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install mkdocs mkdocs-material 
      - run: cd documentation
      - run: mkdocs gh-deploy --force
  deploy_mkdocs:
    runs-on: ubuntu-latest
    needs: install_pipenv_refs
    steps:
      - run: mkdocs gh-deploy --force
